### ISSUE TITLE
Frontend: nachdem Zwischgespeicherte Prüfung wieder geladen wurde ist die grüne Hinterlegung in Schritt 5 weg 

### ISSUE THREAD

**Issue by TimBrander** [ofp-sam-ki/sam-ki-check#26]
- war zuvor noch bei Haken vorhanden

**Comment by larissaeiler** [comment]
Checkbox:
if (this.check.model[firstID][displayName]["checkbox"]) 
                                {checkbox.checked = this.check.model[firstID][displayName]["checkbox"];
                                element.classList.add('table-success');
                                }   


Foto:
 if (vm.check.model[kategorieName] && vm.check.model[kategorieName][schrittName] && vm.check.model[kategorieName][schrittName]["value"]) {
                                    let existingImageData = vm.check.model[kategorieName][schrittName]["value"];
                                    let img = document.createElement("img");
                                    img.src = existingImageData; // Setze die Data URL des gespeicherten Fotos als src-Wert
                                    content.appendChild(img);
                                    element.classList.add('table-success');
                                }
Barcode:
if (this.check.model[kategorieName] && this.check.model[kategorieName][schrittName] && this.check.model[kategorieName][schrittName]["Barcode"]) {
                        let savedBarcode = this.check.model[kategorieName][schrittName]["Barcode"];
                        let codeElement = document.createElement("div");
                        codeElement.textContent = "Barcode: " + savedBarcode;
                        content.appendChild(codeElement);
                        element.classList.add('table-success');
                    }
